### ISSUE TITLE
wireframe - pag ajuda

### ISSUE THREAD

**Issue by JenniferSuelen** [ICEI-PUC-Minas-PMV-SI/pmv-si-2024-1-pe1-t2-desinformacaodigital#21]

**Comment by amandalagep** [comment]
https://www.figma.com/file/OoZxCQ2D3JlEIJZAZrrUKD/P%C3%A1gina-de-ajuda?type=design&node-id=0%3A1&mode=dev&t=DdkD0TSW3CbeIQgg-1
