### ISSUE TITLE
wireframe - pag real ou falso

### ISSUE THREAD

**Issue by JenniferSuelen** [ICEI-PUC-Minas-PMV-SI/pmv-si-2024-1-pe1-t2-desinformacaodigital#23]

**Comment by amandalagep** [comment]
https://www.figma.com/file/QHXzgFX3dZCqocvRi5EQEh/Real-ou-Falso%3F?type=design&node-id=0-1&mode=design&t=3osG0Ngyo5aEJUfa-0

**Comment by amandalagep** [comment]
[Wireframe - Real ou Falso.pdf](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2024-1-pe1-t2-desinformacaodigital/files/14750989/Wireframe.-.Real.ou.Falso.pdf)
